README.md
collector/pom.xml
jmx_prometheus_javaagent/pom.xml
jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
pom.xml

Add Java Agent, to allow running inside the jvm and exposing standard exports.

---

.gitignore
collector/pom.xml
collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/main/java/io/prometheus/jmx/JmxScraper.java
collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
collector/src/test/java/io/prometheus/jmx/TomcatPatternCheckTest.java
collector/src/test/java/io/prometheus/jmx/TomcatServletMBean.java
collector/src/test/resources/logging.properties
example_configs/tomcat.json

Signed-off-by: Peter Rossbach <peterrossbach@me.com>

add some fixes after test jmx_exporter with tomcat 8

---

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/main/java/io/prometheus/jmx/JmxScraper.java

Stop trying to enumerate all possible exceptions, just use
Exception. Catch getMbeanInfo exceptions too. Add stack
traces for logs to help with any future issues.

Catch more exceptions, improve debugability.

---

README.md
collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java

Make an empty name stop rule evaluation.

---

pom.xml

Maybe it works, maybe not :).
No creds, so no way to tell.

Copy pasted code from https://github.com/prometheus/client_java to allow release process

---

collector/src/main/java/io/prometheus/jmx/JmxCollector.java

Added some context information to a possible matcher exception. This eased my debugging, hope it can help others.

Added context to exception to ease debugging.

---

README.md
jmx_prometheus_httpserver/src/deb/bin/jmx_exporter
jmx_prometheus_httpserver/src/deb/config/jmx_exporter.json
jmx_prometheus_httpserver/src/deb/config/jmx_exporter.yaml
jmx_prometheus_httpserver/src/deb/control/control
jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java
jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java

4c0b7dabfa1830221f3806c1785b8791e98a4ef3 blew my mind.

Remove json references and fix deb packaging

---

jmx_prometheus_httpserver/src/deb/bin/jmx_exporter

I also made it executable. Hope that's fine too.

Do exec in jmx_exporter script

---

.gitignore
collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/main/java/io/prometheus/jmx/JmxScraper.java
sample_config.yml

Hope it will be useful for simple JMX authentication, correct me if I miss something.

Added authentication support

---

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
collector/src/test/java/io/prometheus/jmx/GetKeyPropertyListTest.java

Fix for issue #52 - uses regex based on ObjectName spec.

Fix issue #52

---

README.md
collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/main/java/io/prometheus/jmx/JmxScraper.java

This pull request essentially recreates the changes proposed in #12, but against the current codebase.

Implemented arbitrary JMX URLs

---

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/main/java/io/prometheus/jmx/JmxScraper.java
collector/src/test/java/io/prometheus/jmx/BoolMBean.java
collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java

Allows boolean mbeans to be scraped.

Convert boolean mbean values to numbers (true/false => 1/0)

---

collector/pom.xml
jmx_prometheus_httpserver/pom.xml

It would be great if you can also make a new release of jmx_exporter. Thanks!

Update to io.prometheus.simpleclient v0.0.16

---

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java
jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java

Another version of "reload config on change" that checks mtime of the configuration file and tries to load the new configuration, it that fails it keeps running on the previous settings.
Solves #29

Reload configuration when file changes

---

README.md
collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/main/java/io/prometheus/jmx/JmxScraper.java

Hello @brian-brazil ,
This PR enables JMX scraping over SSL. If you have any issues with this, please let me know.
Cheers,
Michal

Allow JMX scraping over SSL

---

run_sample_httpserver.sh

master branch uses 0.9-SNAPSHOT so the bash script should be updated

bump bash script to use 0.9

---

jmx_prometheus_httpserver/pom.xml
jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java
jmx_prometheus_javaagent/pom.xml
jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java

Mainly the same as #95 but without conflicts
mvn integration-test is ok and I use the standalone http server with gzip activated in production

Add gzip compression and bump version on jetty

---

example_configs/flink.yml

We have this config running in production. We use Flink 1.1.4

Add Apache flink example.

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prometheus/jmx_exporter/158)

add ignores for intelliJ

---

README.md

Related to PR #54 and to avoid issues like #136. @brian-brazil

Add username and password options to README.md

---

collector/src/main/java/io/prometheus/jmx/JmxCollector.java

Fix regex wrapper to group user-provided regexp

---

example_configs/spark.yml

* Fixed regex escaping
* Add Structured Streaming metrics
@brian-brazil

Update example config for Spark

---

jmx_prometheus_httpserver/pom.xml
jmx_prometheus_javaagent/pom.xml
jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java

Prevent hanging on exit

---

run_sample_httpserver.sh

@brian-brazil I updated the jmx_prometheus_httpserver jar version to 0.2.1 from 0.1.1 in run_sample_httpserver.sh file to match the latest code version.

Update for 0.2.0

---

collector/src/main/java/io/prometheus/jmx/JmxScraper.java

Follow up to #252. This PR fixes a NullPointerException at JmxScraper.java:240.

Fix NullPointerException at JmxScraper.java:240

---

collector/src/main/java/io/prometheus/jmx/JmxMBeanPropertyCache.java
collector/src/test/java/io/prometheus/jmx/JmxMBeanPropertyCacheTest.java

Prevent StackOverflowErrors when parsing the key property list

---

README.md

This PR will add username and password to readme configuration example.

add username and password to readme configuration example

---

collector/pom.xml

Update client java to 0.6.0

---

example_configs/kafka-2_0_0.yml

Fixed Kafka 2 invalid yaml JMX config
Signed-off-by: spyros87 <papadopoulos.spyridon@gmail.com>

Fixed Kafka 2 invalid yaml JMX config

---

jmx_prometheus_httpserver/pom.xml
jmx_prometheus_javaagent/pom.xml

Dear @brian-brazil check my PR please.

Update version for simpleclient_httpserver to 0.6.0

---

example_configs/kafka-2_0_0.yml

Add kafka.coordinator.* metrics

---

.travis.yml
jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/JavaAgentIT.java
jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/TestJavaAgent.java

Fix tests by splitting integration and unit tests.

---

.circleci/config.yml
.travis.yml

Add circleci for testing. Remove Travis.

---

example_configs/activemq.yml

This example shows how to get Topic, Queue, General metrics via JMX attributes of activemq.

Create an example to get metrics from ActiveMQ

---

example_configs/kafka-connect.yml

Hi @brian-brazil, in this PR I added the exporter metrics file for Apache Kafka Connect.

Add exporter metrics file apache kafka connect

---

example_configs/zookeeper.yaml

fix packet counter pattern in zookeeper sample config

---

collector/pom.xml
jmx_prometheus_httpserver/pom.xml
jmx_prometheus_javaagent/pom.xml

Bump client_java to 0.9.0

---

README.md

Signed-off-by: Shini31 <github@capitoul.net>

Update readme with the new release version (0.13.0)

---

collector/pom.xml

@brian-brazil   #488 fixing security issue [CVE-2017-18640](https://nvd.nist.gov/vuln/detail/CVE-2017-18640)

upgrading snakeyaml to 1.26

---

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java
jmx_prometheus_javaagent_java6/src/main/java/io/prometheus/jmx/JavaAgent.java

This PR implements the proposal from #673.

Prevent remote JMX monitoring when started in agent mode

---

example_configs/kafka-2_0_0.yml

Signed-off-by: maixiaohai <maixiaohai00@gmail.com>
#682 
Fix some percent metrics loss

[ISSUE #682] Add MeanRate Percent metrics for kafka in example config

---

MAINTAINERS.md

Thanks Doug for becoming a maintainer of `client_java` and `jmx_exporter`!

Add Doug Hoard as maintainer

---

example_configs/helix.yml

I created this configuration to allow for our helix deployment to report metrics to prometheus. Figured it would be helpful for other folks as getting it to work was non-trivial.

feat: adding apache helix as an example

---

integration_test_suite/integration_tests/pom.xml

Decreased test engine thread count due to seeing CircleCI build failures regarding memory usage.

Decreased test engine thread count

---

integration_test_suite/integration_tests/pom.xml
integration_test_suite/integration_tests/src/test/resources/docker-image-names.txt

Changed list of smoke test Docker images to constrain memory usage when running in CircleCI

Changed list of smoke test Docker images

---

.gitignore
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/HttpHeader.java
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/MetricsParser.java
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/BaseResponse.java
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/HealthyRequest.java
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/HealthyResponse.java
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/MetricsResponse.java
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/OpenMetricsResponse.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/Abstract_IT.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/AutoIncrementing_IT.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/LowerCaseOutputAndLabelNames_IT.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/Minimal_IT.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/WhitelistObjectNames_IT.java
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/AutoIncrementing_IT/JavaAgent/application.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/AutoIncrementing_IT/JavaAgent/application_java6.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/AutoIncrementing_IT/JavaAgent/exporter.yaml
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/AutoIncrementing_IT/Standalone/application.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/AutoIncrementing_IT/Standalone/application_java6.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/AutoIncrementing_IT/Standalone/exporter.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/AutoIncrementing_IT/Standalone/exporter.yaml
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/AutoIncrementing_IT/Standalone/exporter_java6.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/WhitelistAndBlacklistObjectNames_IT/Standalone/exporter.yaml
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/WhitelistObjectNames_IT/JavaAgent/exporter.yaml
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/AutoIncrementing.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/AutoIncrementingMBean.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/JmxExampleApplication.java
stress-test.sh

Fixed incorrect test container logic that allowed tests to start before the container was fully started. This would result in random test failures.

Fixed incorrect test container logic

---

README.md
integration_test_suite/integration_tests/pom.xml

Dependency updates

---

integration_test_suite/integration_tests/pom.xml
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/BaseTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPBKDF2WithHmacSHA1Test.java

* Updated AntuBLUE Test Engine version
* General cleanup

Updated AntuBLUE Test Engine version

---

README.md
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/threads/ThreadsConfigurationTest.java
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/http/threads/ThreadsConfigurationTest/JavaAgent/application.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/http/threads/ThreadsConfigurationTest/JavaAgent/exporter.yaml
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/http/threads/ThreadsConfigurationTest/Standalone/application.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/http/threads/ThreadsConfigurationTest/Standalone/exporter.sh
integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/http/threads/ThreadsConfigurationTest/Standalone/exporter.yaml
jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/http/HTTPServerFactory.java

Resolves https://github.com/prometheus/jmx_exporter/issues/720

Added HTTPServer threads configuration and integration test

---

collector/src/main/java/io/prometheus/jmx/JmxScraper.java

Added code to skip MBean values that are not of type `javax.management.Attribute`
Cleaned up scrapeBean method (naming, formatting, added additional `FINE` logging.)

Added code to skip MBean values that are not of type javax.management.Attribute

---

jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/http/authenticator/PBKDF2Authenticator.java
jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/util/Precondition.java
jmx_prometheus_common/src/test/java/io/prometheus/jmx/common/util/PreconditionTest.java

Cleaned up Precondition logic. Added test

---

README.md
jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/http/HTTPServerFactory.java

Changed default maximum threads to 10.

Changed default maximum threads

---

collector/src/main/java/io/prometheus/jmx/JmxScraper.java

Added a check for a NULL in the AttributeList.

Fix NullPointerException during scrape

---

collector/pom.xml
integration_test_suite/integration_tests/pom.xml
integration_test_suite/pom.xml
jmx_prometheus_common/pom.xml
jmx_prometheus_httpserver/pom.xml
jmx_prometheus_javaagent/pom.xml
pom.xml

Updated Maven dependencies

---

collector/pom.xml
integration_test_suite/integration_tests/pom.xml
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/metrics/MetricsParser.java
integration_test_suite/jmx_example_application/pom.xml
pom.xml

Updated dependencies

---

collector/src/test/java/io/prometheus/jmx/DuplicateLabels.java

Added duplicate labels test

---

collector/src/test/java/io/prometheus/jmx/DuplicateLabels.java

Disabled test code

---

jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/http/HTTPServerFactory.java
jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/util/Precondition.java
jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/yaml/YamlMapAccessor.java

Fixed Javadoc warnings

---

MAINTAINER_NOTES.md
README.md
collector/pom.xml
collector/src/test/java/io/prometheus/jmx/DuplicateLabels.java
docs/README.md
integration_test_suite/integration_tests/pom.xml
integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/TestContext.java
integration_test_suite/jmx_example_application/pom.xml
integration_test_suite/pom.xml
jmx_prometheus_common/pom.xml
jmx_prometheus_httpserver/pom.xml
jmx_prometheus_javaagent/pom.xml
pom.xml

PR that integrates client_java 1.3.0.

client_java 1.3.0 integration

---

integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/metrics/MetricsParser.java

Fixed integration test help parsing to include complete information.

Fixed integration test help parsing

---

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/main/java/io/prometheus/jmx/MatchedRule.java
collector/src/main/java/io/prometheus/jmx/MatchedRuleToMetricSnapshotsConverter.java
collector/src/test/java/io/prometheus/jmx/CollidingNameMBean.java
collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
collector/src/test/java/io/prometheus/jmx/TotalValueMBean.java

Experimenting with a solution to #958.
@dhoard this is work-in-progress, but I'm wondering what you think of the general approach?

Issue 958 / Handle name collisions

---

integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/metrics/MetricAssertion.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/CompositeKeyDataTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/MinimalTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/OptionalValueMBeanTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/CompleteHttpServerConfigurationTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/AbstractBasicAuthenticationTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPBKDF2WithHmacSHA1Test.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPBKDF2WithHmacSHA256Test.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPBKDF2WithHmacSHA512Test.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPlaintextTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationSHA1Test.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationSHA256Test.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationSHA512Test.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLAndBasicAuthenticationPBKDF2WithHmacSHA512Test.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithJKSKeyStoreMultipleCertificatesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithJKSKeyStoreTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithJKSKeyStoreTest2.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithPKCS12KeyStoreMultipleCertificatesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithPKCS12KeyStoreTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithPKCS12KeyStoreTest2.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/threads/ThreadsConfigurationTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/rmi/ssl/MinimalRMISSLTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/rmi/ssl/RMIRegistrySSLDisabledTest.java

Refactored integration tests, removing commonality.
Refactored `MetricAssertion` for clarity.

Refactored integration tests

---

integration_test_suite/integration_tests/pom.xml

Updated AntuBLUE test engine

---

integration_test_suite/integration_tests/pom.xml

Updated AntuBLUE test engine to 7.0.0

Updated AntuBLUE test engine to 7.0.0

---

integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/AuthenticatorClassTest.java

Fixed import to reference latest Verifyica coordinates.

Fixed import

---

collector/pom.xml
integration_test_suite/integration_tests/pom.xml
integration_test_suite/jmx_example_application/pom.xml
integration_test_suite/pom.xml
jmx_prometheus_common/pom.xml
jmx_prometheus_httpserver/pom.xml
jmx_prometheus_javaagent/pom.xml
pom.xml

Changed version to represent that the next release is post 1.0.1.

Changed version

---

collector/src/main/java/io/prometheus/jmx/ObjectNameAttributeFilter.java
collector/src/test/java/io/prometheus/jmx/ObjectNameAttributeFilterTest.java

Disable auto exclude to work around potential merge of unstable code.

Disable auto exclude

---

integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/BlacklistObjectNamesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/CompositeKeyDataTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/DisableAutoExcludeObjectNameAttributesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/ExcludeObjectNameAttributesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/ExcludeObjectNamesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/IncludeAndExcludeObjectNamesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/IncludeObjectNameAttributesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/IncludeObjectNamesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/LowerCaseOutputAndLabelNamesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/LowerCaseOutputLabelNamesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/LowerCaseOutputNamesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/WhitelistAndBlacklistObjectNamesTest.java
integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/core/WhitelistObjectNamesTest.java

Cleaned up integration tests, removing unused arguments.

Cleaned up integration tests

---

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
collector/src/main/java/io/prometheus/jmx/MatchedRulesCache.java

This PR improves performance of jmx_exporter when caching is enabled while also making the cache smaller. The improvements come primarily from:
* Instead of having and checking separate cache for each rule, we now have one cache that contains the match from the first matching cacheable rule or an unmatched value if none of the cacheable rules match. This means that the performance and cache size won't degrade as the number of rules increases.
* Avoiding construction and manipulation of string when looking up the cache. These operations are delayed until necessary, and avoided completely if a cache entry is found. This way allocation rate is greatly reduces easing out the pressure on GC.
* Avoiding `String#intern` which while hugely beneficial for decreasing the size of the cache under …

Redesign cache for better performance

---

integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/AutoIncrementing.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/AutoIncrementingMBean.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/CustomValue.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/CustomValueMBean.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/ExistDb.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/ExistDbMXBean.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/JmxExampleApplication.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/OptionalValue.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/OptionalValueMBean.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/PerformanceMetrics.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/PerformanceMetricsMBean.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/StringValue.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/StringValueMBean.java
integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/TabularData.java

Refactored example application MBeans into separate interface and implementation classes.

Refactored example application

---

integration_test_suite/integration_tests/src/test/resources/prometheus-docker-images.txt
integration_test_suite/integration_tests/src/test/resources/smoke-test-prometheus-docker-images.txt
run-quick-test.sh

Added Prometheus 3.4.0 Docker test image

Updated Prometheus Docker images

---

jmx_prometheus_isolator_javaagent/src/main/java/io/prometheus/jmx/IsolatorJavaAgent.java
jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java

Added code to force initialization of the platform MBean server in the correct classloader. Required for future feature to disable JVM metrics.

Added code to force initialization of the platform mbean server

---

collector/src/main/java/io/prometheus/jmx/logger/Logger.java
collector/src/main/java/io/prometheus/jmx/logger/LoggerFactory.java
jmx_prometheus_isolator_javaagent/src/main/java/io/prometheus/jmx/logger/Logger.java
jmx_prometheus_isolator_javaagent/src/main/java/io/prometheus/jmx/logger/LoggerFactory.java

Cleaned up logging to use JUL.
If the formatter is `java.util.logging.SimpleFormatter`, use a custom formatter.

Cleaned up logging
