prometheus/jmx_exporter

README.md, collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
Lowercaseing labels avoids mixing camelcase with the more common snake case in Prometheus.
Do a straight lowercase, as converting to snakecase would produce confusing names in most cases.
Allowing empty labels makes it easier to combine rules where some attributes may not be present in some cases.
=> Support lowercasing names and labels. Allow for empty labels.

README.md, jmx_prometheus_javaagent/pom.xml
This is a strange one and I'm not sure whether it's my version of maven.
If you've already run `mvn package` at least once, then subsequent `mvn package` commands without `clean` causes the Maven Shade plugin to use the combined jar file, rather than the original.
I.e, It doubles up the shading in the jar which causes some weird issues.  For instance, running on tomcat, I get this error message with the bad jar:
```
Exception in thread "main" java.lang.ClassNotFoundException: io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent
```
`mvn clean package` works fine.
This fix also changes the output file to be more in-line with the http server project.
=> Change output filename on java agent to prevent double shading of the jar

jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
This makes sure Jetty uses daemon threads for clean exit when the JVM stops. It prevents Cassandra hanging on startup when using the agent with the standard Cassandra start scripts. For more background see https://issues.apache.org/jira/browse/CASSANDRA-7254
Before this PR running "java -javaagent:jmx_prometheus_javaagent-0.3-SNAPSHOT.jar=7070:jmx_exporter.json" results in the JVM showing usage text and then not exiting properly. After PR it exits cleanly. (and this is exactly what the cassandra start scripts do)
=> use daemon threads for jetty

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
Simply contains an exception catch for something that was being thrown when I tried to connect to the jmx connector of Bamboo. mvn package and mvn test worked for me
=> ISSUE-17: Added a catch for UnmarshalException

collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
CollectorRegistry.getSampleValue assumes that the labelNames ordering
matches that of what was provided in the sample. While this is generally
workable, it's not true when it's coming from an unordered JSON map.
See https://github.com/prometheus/client_java/issues/71
Workaround this by sorting the labels we get.
=> Workaround lack of ordering in JSONObject.

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
Currently the code does not compile, because a Map cannot be instantiated.
=> Fix compiler error: trying to instantiate a Map directly

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
It's not currently possible to connect to servers that use credentials, because the credentials are configured incorrectly:
The key for credentials is not `"javax.management.remote.JMXConnector.CREDENTIALS"`, but `javax.management.remote.JMXConnector.CREDENTIALS` (which is in fact equal to `"jmx.remote.credentials"`).
Also, credentials must be passed in as an array, rather than as a list.
The attached pull request rectifies these issues.
=> Cannot connect when using credentials

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
Solves #89 
No noticable performance impact when testing scrape of a target with about 1800 MBeans.
=> Use queryMBeans instead of queryNames.

jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
On a JVM where a scrape goes over Prometheus' scrape_timeout due to high load, Prometheus may hit the target again before the initial thread completes the scrape, contributing to the high load.
The default number of threads QueuedThreadPool will create is 254. Having this much scrapes in parallel cause high memory usage when there are many JMX beans to scrape, potentially tipping the server over its max heap size, and also contributing to CPU load because of full GC.
Setting the max number of threads to 10 provides enough to the server for accepting connections and handling few of them before queuing. This could be configurable, but I don't see any use-case.
I've also set the thread pool name to "jmx_exporter", so we get "jmx_exporter-182" instead of "qtp22756955-182" in thread dumps.
=> Set the maximum number of threads and queue size to 10 to avoid app DoS

jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
Explicitly set number of acceptors used by Jetty to 1, to avoid Jetty failing to start when there are more acceptors than threads in the thread pool. Fixes #122.
=> Explicitly set number of acceptors

example_configs/kafka-0-8-2.yml
This fixes the example kafka rules to parse all (on my system) mbeans and move all dynamic fields like brokerhost, port, thread ids etc into labels.
I also reversed the order of two rules, as the first matching pattern wins and the second rule was more concrete.
ping @brian-brazil
=> Fix order of example rules and add more labels

README.md, collector/src/main/java/io/prometheus/jmx/JmxScraper.java
It is often useful when there is a lot of jmx entries available to time them in order to exclude those that take a lot of time (i.e: Cassandra).
This PR add the options --time_jmx_call to do so.
Feel free to comment if it not to your taste.
=> Add options to time jmx_call when running in standalone

jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java, jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/JavaAgentIT.java, jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/TestApplication.java
Fixing my mistakes for the gzip compression with the java agent.
My apologies for not having tested more the first time, I was lured by the test.
+ Don't create an InetSocketAddress as it will be created by the connector
+ Ask jetty to shutdown properly when the app stop
+ Fix integration test, as now jetty keeps the connection alive
+ Fail integration test if  scraping goes wrong (ie: connection refused)
P.s: The Systemd.exit(0) in the TestApplication is needed only when the app is run with maven. When launched directly with the javaagent it will stop gracefully without the systemd.exit(0)
=> Gzip compression fixing my mistakes

README.md, collector/src/main/java/io/prometheus/jmx/JmxCollector.java
Hi @brian-brazil,
the current version of the jmx_exporter uses the type gauge for all metrics that match a rule that has no name configured and not the type configured for the rule. This PR fixes this.
=> Use the type provided by the rule for the defaultExport

.gitignore, README.md, collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
@brian-brazil:
This is a first pass implementation of configurable startup delay for the JVM Agent.
It is intended to resolve #97 and #128
A few notes:
* There are no tests at this time (I will correct this shortly)
* There is no documentation for the property (coming)
* I had to implement the _Describable_ interface in the _Collector_ and return an empty list, breaking current behaviour which 'auto describes' JMX beans. This is only because the act of registering the JMX Collector results in a call to _collect_ as a side-effect. In my particular case it was important not to call _ManagementFactory.getPlatformMBeanServer_ before the delay expires (this is what resolves #128).
The way the code is currently structured, configuration is done at startup time and it is only the Agent Web …
=> [Feature] configurable startup delay

jmx_prometheus_httpserver/pom.xml, jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java, jmx_prometheus_javaagent/pom.xml, jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java, jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/JavaAgentIT.java, jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/TestApplication.java
It is reverting the following
+ Gzip compression
+ Usage of ReuseAddress port for the http server
+  bump of maven-shade plugin
This reverts commit 
e4f8280b52ac208c24ebbff4fb1be28ea0fe667d
fde351f805e46b59f85d76fcee07ffa93c83aef6
=> Revert: "Add gzip compression on jetty (#137, #139)" to restore java 1.6 compatibility

.gitignore, collector/pom.xml, jmx_prometheus_httpserver/pom.xml, jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java, jmx_prometheus_javaagent/pom.xml, jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
Motivation:
https://github.com/prometheus/jmx_exporter/issues/155
Modifications:
Changed the code of both the agent and external HTTP process to use the simple HTTP server provided on https://github.com/prometheus/client_java/pull/73
Result:
JMX exporter works with the simple HTTP Server.
=> Use simple HTTP Server

README.md
The `^` is added to the pattern in the code, so I guess it is redundant.
https://github.com/prometheus/jmx_exporter/blob/a7b038f90f7b49dda1f9bfaf4089f159f0686d6e/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L170
I am getting following exception, when using double quotes:
```
"jboss.jca<service=ManagedConnectionPool, name=(\w+)><>AvailableConnectionCount: (\d+)"
```
```
Exception in thread "main" while scanning a double-quoted scalar
in 'reader', line 9, column 12:
- pattern: "jboss.jca<service=ManagedConnec ...
^
found unknown escape character w(119)
in 'reader', line 9, column 61:
... e=ManagedConnectionPool, name=(\w+)><>AvailableConnectionCount:  ...
^
at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1906)
at …
```
=> Fix rule pattern in README.md

jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/JavaAgentIT.java
The original Integration-Test would not work on Windows systems.
=> make test platform-independent

README.md
As discussed in issue #111, it is not intended that the JMX exporter
extracts generic JVM metrics when running as a separate process. These
values are only exposed when running the exporter as an agent as part of
the process to be monitored.
=> Document that running as an agent is required for generic JVM metrics.

example_configs/weblogic.yml
This PR is just an example of jmx_exporter working with WebLogic.
The tricky part is in the jmxUrl format.
With this configuration, you can retrieve almost all important internals metrics of WebLogic (datasource, jms, gc activity, JVM memory, etc.).
=> Add an example of weblogic configuration.

jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
This enables bind to IPv6 address in square brackets:
```
-javaagent:/usr/share/jmx_exporter/agent.jar=[f00::123]:9097:/etc/kafka/jmx-exporter.yaml
```
=> Support for IPv6 bind

example_configs/artemis-2.yml
@brian-brazil I added an example for Apache ActiveMQ Artemis. It only works for version newer than 2 because they changed the JMX MBean object names in this version.
Best regards
Niko
=> Added Apache ActiveMQ Artemis 2.x example

collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/test/java/io/prometheus/jmx/SnakeCaseAttrTest.java
A small improvement to address https://github.com/prometheus/jmx_exporter/issues/233
@brian-brazil You can see the difference here for yourself: https://github.com/afalko/testrepo/blob/master/TimingBench.java
The bottom result is the new method:
```
$ java TimingBench
start_time_$1_$2
507
start_time_$1_$2
149
```
=> Replace expensive snakeCase regex transform

README.md
A minor fix to README to ensure the same port is not being monitored and used to serve the metrics.
=> Clearly distinguish between http and jmx ports

README.md, collector/pom.xml, jmx_prometheus_httpserver/pom.xml, jmx_prometheus_javaagent/pom.xml, pom.xml
Switch to JDK 6 as baseline for all modules.
This fixes the following issues, and simplifies project setup (no JDK baseline mix, project wide Maven compiler plugin configuration):
- The collector module declares JDK 5 target but uses JDK 6 API:
In collector/src/main/java/io/prometheus/jmx/JmxCollector.java L223, L343, L370, L395 :
[isEmpty() is JDK 6 String API](https://docs.oracle.com/javase/6/docs/api/java/lang/String.html#isEmpty())
- The collector module also uses simpleclient, which compiles for JDK 6.
- The module jmx_prometheus_httpserver also compiles for JDK 5, but requires collector module. Therefore min version is also JDK 6.
=> Require JDK 6 for compiling and running

collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/test/java/io/prometheus/jmx/SafeNameTest.java
I'm trying to prevent this exception from ever happening again: 
```
SEVERE: JMX scrape failed: java.lang.IndexOutOfBoundsException: start
31, end 0, s.length() 137
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
at java.lang.StringBuffer.append(StringBuffer.java:350)
at java.util.regex.Matcher.appendReplacement(Matcher.java:888)
at java.util.regex.Matcher.replaceAll(Matcher.java:955)
at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector$Receiver.recordBean(JmxCollector.java:358)
at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.processBeanValue(JmxScraper.java:181)
at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:149)
at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:110)
at …
```
=> Replace safeName regex to avoid IndexOutOfBoundsException

run_sample_httpserver.sh
`0.2.1-SNAPSHOT` didn't cut it anymore. Use the current `SNAPSHOT` version from `pom.xml` to always be up to date.
=> Use the version in pom.xml to run the sample HTTP server

README.md
Both the download link and command line example were still using 0.2.0.
=> README: Update example usage with version 0.3.0

collector/src/main/java/io/prometheus/jmx/BuildInfoCollector.java, collector/src/test/java/io/prometheus/jmx/BuildInfoCollectorTest.java, jmx_prometheus_httpserver/pom.xml, jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java, jmx_prometheus_javaagent/pom.xml, jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
By adding the Implementation-Version manifest entry it is possible
to retrieve the lib version at runtime by checking the class Package.
This allows the tracking of which JVMs are running which versions of
the exporter.
Closes #278
=> Registering JMX Exporter build info

jmx_prometheus_javaagent/pom.xml
This downgrade allows JMX Exporter to keep compatible with Java 6.
The version 1.9.1 of build-helper-maven-plugin is the last version compatible with Java 6.
By accepting this change, issue #281 and PR #282 become not necessary and can be closed as well.
=> Downgrading maven builder helper plugin to 1.9.1

jmx_prometheus_javaagent/pom.xml, jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
By adding the agentmain method, we enable the ability of attaching
the JMX Exporter Java Agent to a JVM after the VM starts, providing
a more dynamic approach to managing thousands of deployed VMs.
Usage example:
```
VirtualMachine vm = VirtualMachine.attach(processPID);
vm.loadAgent("./jmx_prometheus_javaagent-0.3.2.jar=8080:config.yaml");
vm.detach();
```
Important to note that this change does not break any of the existing behaviours of the agent nor it adds any extra responsibility to it, it only enables this ability on top of it.
@brian-brazil Can you please review? Could this be something that we could add to the agent?
=> Make the agent attachable to a running VM

example_configs/wildfly-10.yaml
see https://github.com/prometheus/jmx_exporter/issues/246#issuecomment-367573931
With this patch, the scrape time (`jmx_scrape_duration_seconds`) dropped from 15 seconds to 0.9s. (using with jmx_explorer 0.7)
I can therefore avoid increasing  `scrape_timeout` and `scrape_interval`.
Signed-off-by: Frank Lin Piat <fpiat@klabs.be>
=> wildfly : Whitelist objects for performance reason

example_configs/kafka-2_0_0.yml
This is based on kafka-0_8_2.yml, with changes to better work with Kafka 2.0:
* "Histograms" are exposed as summaries (without the _sum)
Note that this changes some metrics to now have a _count suffix compared to
what kafka-0_8_2.yml would provide!
* Simplifications to capture the structure of "name, type" + "one or two labels"
better
---
Here's a example list of metrics for comparison/understanding the available dimensions: 
[example-metrics.txt](https://github.com/prometheus/jmx_exporter/files/2257502/example-metrics.txt)
=> Add an example configuration for Kafka 2.0.0

example_configs/spark.yml
- Updates spark example supporting histograms and timers.
- Also covers jvm metrics previously ignored.
Some examples follow of the available metrics exposed by driver/executors and need coverage:
Also here are some properties that are either a timer or a histogram:
I tested this by verifying all metrics are captured using Spark on K8s.
=> Update spark yaml

example_configs/cassandra.yml
@brian-brazil 
Inspired by the kafka-2_0_0.yml configuration
* Latency histograms are exported as emulated Summaries.
* Otherwise, histograms exported as Summaries without the _sum.
List of example metrics: [cassandra-example-metrics.txt](https://github.com/prometheus/jmx_exporter/files/2516302/cassandra-example-metrics.txt)
There a ***lot*** of metrics exposed by default. In our implementation, we utilize several whitelistObjectNames values to only capture the specific metrics that we need. Otherwise, it presents a fairly heavy load on the exporter. I didn't want to restrict that outright. Instead, let the users determine which metrics they want to see.
=> Update the Apache Cassandra example configuration

collector/src/main/java/io/prometheus/jmx/JmxScraper.java, collector/src/test/java/io/prometheus/jmx/HadoopDataNodeMXBean.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
Don't lose the key label from the outer data,
rather ensure there's unique label names.
Fixes #347 
=> Handle nested tabular data.

collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/test/java/io/prometheus/jmx/SafeNameTest.java
Only characters `a-zA-Z0-9_:` is allowed for names and labels.
The current use of `Character.isLetterOrDigit` supports Unicode characters (within the Basic Multilingual Plane) which lets names using invalid characters through (e.g. use of Swedish letters åäö).
I find this change trivial one, so according to `CONTRIBUTING.md` I went straight ahead and made a pull request. @brian-brazil please review.
=> Stricter safename

jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
When the agent starts up, you get the same output no matter what is wrong:
```
Usage: -javaagent:/path/to/JavaAgent.jar=[host:]<port>:<yaml configuration file>```
```
This patch adds the exception to the output:
```
Usage: -javaagent:/path/to/JavaAgent.jar=[host:]<port>:<yaml configuration file> At most one of hostPort and jmxUrl must be provided
```
cc @brian-brazil,
=> include error message with exception

jmx_prometheus_javaagent/pom.xml, jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
Hi @brian-brazil 
There is an item I want to see, but it isn't there. (e.g, jvm_threads_state)
I found the simpleclient_hotspot version is too low to see in javaagent.
=> Update simpleclient_hotspot version (#400)

README.md
With the 0.12.0 jar, you have to use the full shaded package path to run JmxScraper standalone.
=> Clarify how to use JmxScraper standalone

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
@brian-brazil adding support for reading the collector's configuration from an ``InputStream``. This is handy if you want to read the config from an archive in the classpath, eg. using Spring's ``ResourceLoader``:
```java
try(InputStream is = loader.getResource("classpath:/collect.yml").getInputStream()) {
collectorRegistry.register(new JmxCollector(is));
}
```
=> Allow collector configuration from InputStream

example_configs/kafka-2_0_0.yml
@brian-brazil adding metrics for quotas of client-id and/or user for Apache Kafka config exemples. This patter alredy is working in my environment. However this is metrics only appears when the quotas they are enebled. 
Link of documentation:
https://kafka.apache.org/documentation/#remote_jmx
=> Add metrics quota kafka for client-id or/and user

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
Hey @brian-brazil, this resolves #362.
=> Handle NullPointerException for getAttributes

collector/src/main/java/io/prometheus/jmx/JmxScraper.java, collector/src/test/java/io/prometheus/jmx/CamelMBean.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
Dear maintainers,
We recently had an requirement to expose certain JMX attributes of java Date type to prometheus, specifically, a number of timestamps in the built-in JMX of Apache Camel library.
We thought that it might be useful for other users of the exporter, would you review our changes and let us know any feedbacks and critics please?
Thank you
Jacky
=> added support on jmx attributes of type java.util.Date

README.md
Sorry, I did not realize that I created this PR for the wrong repo.
fixes #175
=> Add a note on slow /metrics endpoint

example_configs/wildfly-10.yaml
Without this fix only exact "jboss.as:subsystem=messaging-activemq,server=*" objects were found, all having one more identifier (like jms-queue or jms-topic) were not found.
@brian-brazil please, take a look (I'm tagging you according to the process described in Contributing file for trivial fixes)
I've checked this fix on Java8 + WildFly13
=> fix objectName pattern for messaging queues

example_configs/wildfly-10.yaml, jmx_prometheus_httpserver/src/main/java/io/prometheus/jmx/WebServer.java
Small change that allows to add IPv6 hosts
=> Possibility to add IPv6 as a parameter for http server

example_configs/zookeeper.yaml
Hi,
Example for zookeeper rules has no metric type. When accessing _/metrics_ endpoint all zookeper's metrics have **untyped** type. It is a problem for some use cases when metric type is used in parsing logic.
=> Add metric type for zookeeper rules

jmx_prometheus_javaagent/src/test/java/io/prometheus/jmx/JavaAgentIT.java
Hi guys! 
You build the important staff, we are using your tool for our ActiveMq instance.
I made a little fix for this:
https://github.com/prometheus/jmx_exporter/issues/405
=> Fix incorrect 'java' path when JAVA_HOME isn't empty

README.md, collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/main/java/io/prometheus/jmx/MatchedRule.java, collector/src/main/java/io/prometheus/jmx/MatchedRulesCache.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
This improves performance for some use cases.
The exporter is configured with a set of rules to match regular
expressions against bean names. Regular expressions can be CPU-intensive,
and matching the same bean names over the same patterns is
time-consuming when there are tens of thousands of bean names (e.g:
exposed by Kafka). Using a single `ConcurrentHashMap` to store the result
of pattern matching here.
The `MatchedRule` class was introduced here to "store" this result.
Each rule in the configuration leads to a `MatchedRule` which helps
build the set of metrics to expose to Prometheus.
The mapping between a bean name + attributes to a `MatchedRule` is
done once. Some (in Kafka, most) bean names may not match any rule,
so caching of `MatchedRule.unmatched()` helps prevent …
=> Allow caching regular expression matching in rules

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
Added a sanitary check to the JMX Scraper so that it will skip Attributes processing that are not javax.management.Attribute types. This is an issue present in Apache Ignite, when there are some Attributes that are of type javax.management.openmbean.TabularDataSupport
Signed-off-by: Neville Bonavia <neville.bonavia@gig.com>
The error log in such a situation is: -
Oct 08, 2020 1:28:28 PM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.lang.ClassCastException: javax.management.openmbean.TabularDataSupport cannot be cast to javax.management.Attribute
at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:163)
at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:542)
at …
=> SEVERE: JMX scrape failed: java.lang.ClassCastException: javax.management.openmbean.TabularDataSupport cannot be cast to javax.management.Attribute

example_configs/spark-3-0.yml
- added "type" value to Regex so resulting prometheus metrics are identical to spark 2.4 version
@brian-brazil 
i don't know the details, but it seems that a "type=counters" or "type=gauge" has been added to the JMX metrics of spark in 3.0 version.
So i added this type strings to the regex to emit this value from the resulting prometheus metric name so we have a config for spark 2.4 and 3.0 resulting in the same metric names.
=> updated spark example config for spark 3.0

collector/pom.xml, collector/src/main/java/io/prometheus/jmx/JmxCollector.java, jmx_prometheus_httpserver/pom.xml, jmx_prometheus_javaagent/pom.xml
Transparently handle the UNTYPED->UNKNOWN switch for users.
Change snakeyaml version to 1.23 so Java 6 works again, fixes #537.
=> Update to client_java 0.10.0 and OpenMetrics.

MAINTAINERS.md
Yesterday at the dev-summit, the Prometheus team has proposed @fstab and @tomwilkie as the new maintainer for this repo after @brian-brazil's retirement from the project.
This change will only be merged after an announcement on the prometheus-developers mailing list and is subject to lazy consensus.
Thank you, @brian-brazil, for the incredible amount of work done in this repository and for the project in general.
=> Change maintainer from @brian-brazil to @fstab and @tomwilkie

collector/pom.xml
A vulnerability scan of the prom/jmx_exporter image finds this.
CVE | SEVERITY | CVSS | PACKAGE | VERSION | STATUS | PUBLISHED | DISCOVERED | DESCRIPTION
-- | -- | -- | -- | -- | -- | -- | -- | --
CVE-2017-18640 | high | 7.50 | org.yaml_snakeyaml | 1.17 | fixed in 1.26 | > 10 months | < 1 hour | The Alias feature in SnakeYAML 1.18 allows entity expansion during a load operation, a related issue to CVE-2003-1564.
@brian.brazil@robustperception.io
=> Bump snakeyaml to 1.27

collector/src/main/java/io/prometheus/jmx/JmxScraper.java, collector/src/main/java/io/prometheus/jmx/OptionalValueExtractor.java
The SonarQube maintainers had this weird idea of an `Optional<Long>` property in an mbean:
https://github.com/SonarSource/sonarqube/blob/8.7.0.41497/server/sonar-ce/src/main/java/org/sonar/ce/monitoring/CeTasksMBean.java#L37
(IMHO, having a regular `long` property, and returning `0` when no task is currently pending, would have been fine too, but that's how it is...)
This currently can't be scraped via the `jmx_exporter` JVM agent. So here we go, a modest proposal to support `java.util.Optional`, of course only when the agent runs on Java 8+. This implementation uses Java reflection to find the `java.util.Optional` class and its `orElse(Object)` method. If found, then when an mbean property `value` is indeed an `Optional`, it will be processed as `value.orElse(null)`.
Caveats:
- don't …
=> Add support for java.util.Optional MBean properties

collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java
Fix allowing to retain the configured 'help' content when rule is cached (fixes #612).
@fstab , @tomwilkie , feel free to elaborate on this one - let me know if there is any change needed in this pull request.
=> Leverages the interpolated help when the matching rule is cached (fixes #612)

pom.xml
I'm facing this issue: [WARNING: sendResponseHeaders: being invoked with a content length for a HEAD request #685](https://github.com/prometheus/client_java/issues/685)
client_java 0.13.0 including this fix
=> Update to client_java 0.13.0

README.md, collector/src/main/java/io/prometheus/jmx/JmxCollector.java
Including the whole mBean fully qualified name can produce a huge amount
of HELP metadata cardinality, slowing down the UI and bloating the TSDB
indexes.
Fixes: https://github.com/prometheus/jmx_exporter/issues/703
Signed-off-by: SuperQ <superq@gmail.com>
=> Reduce cardinality of default help strings

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
Last command line argument can be the string literal "ssl" to enable ssl.
System properties `-Djavax.net.ssl.keyStore=… -Djavax.net.ssl.keyStorePassword=… -Djavax.net.ssl.trustStore=… -Djavax.net.ssl.trustStorePassword=…` still need to be manually set.
=> Add support in JmxScraper for ssl

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
=> issue-695: revert bulk loading of attributes

example_configs/kafka-2_0_0.yml
Quotas can be specified in tupples (user, client-id). The user and client-id can also be used isolated.
So added the missing rule.
@fstab
@tomwilkie
=> fix(examples): add missing kafka quota pattern

integration_tests/smoke_tests/src/test/java/io/prometheus/jmx/AgentJavaVersionsIT.java, integration_tests/smoke_tests/src/test/java/io/prometheus/jmx/HttpServerIT.java, jmx_prometheus_httpserver/pom.xml, jmx_prometheus_httpserver_java6/pom.xml
Fixed packaging to add version and name to build info metric for the HTTP server. (The Agent builds work correctly.)
Added integration tests to validate that the name is correct and that the version is not "unknown" for all builds.
https://github.com/prometheus/jmx_exporter/issues/728
=> Fixed packaging to add version and name to build info metric

jmx_prometheus_httpserver/src/deb/control/control
- Since 77a5b8fe17520a097429cf5f47021990c0eb6438, "name" is "Prometheus
JMX Exporter - Http Server", which break debian package generation
- use artifactId to get a correct name
=> Use artifactId to generate debian package name

collector/src/main/java/io/prometheus/jmx/BuildInfoCollector.java
Refactored `BuildInfoCollector` for optimization. The build information is static for a jar, so rebuilding it on every collection isn't required.
=> Refactored `BuildInfoCollector` for optimization

collector/src/main/java/io/prometheus/jmx/JmxCollector.java
Changed logic to only create an attribute's snake case name if required by the rule.
https://github.com/prometheus/jmx_exporter/issues/822
=> Attribute snake name creation logic

collector/src/main/java/io/prometheus/jmx/JmxScraper.java, collector/src/test/java/io/prometheus/jmx/ExistDbMXBean.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/CompositeKeyDataTest.java, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/CompositeKeyDataTest/JavaAgent/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/CompositeKeyDataTest/JavaAgent/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/CompositeKeyDataTest/Standalone/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/CompositeKeyDataTest/Standalone/exporter.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/CompositeKeyDataTest/Standalone/exporter.yaml, integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/ExistDbMXBean.java, integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/JmxExampleApplication.java
Previously the implementation for JMX TabularData did not support TabularData that used composite keys. This PR adds support for that. It also adds a test that should show that this now works.
In eXist-db, we often export data via JMX that uses composite keys for Tabular Data. There is nothing in this PR that is specific to eXist-db, and I suspect the improved functionality in this PR will be be generally useful for all JMX users.
=> Add support for JMX TabularData that uses a CompositeData key

integration_test_suite/integration_tests/pom.xml, integration_test_suite/jmx_example_application/pom.xml, jmx_prometheus_httpserver/pom.xml, jmx_prometheus_javaagent/pom.xml
These changes make copying the `jmx_prometheus_javaagent.jar`, `jmx_prometheus_httpserver.jar`, and `jmx_example_application.jar` a concern of their respective projects.
This allows patching of the `integration_tests` jars and building/running the integration test suite on older or pre-release jars.
=> Changed integration test build

README.md, collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/main/java/io/prometheus/jmx/JmxScraper.java, collector/src/test/java/io/prometheus/jmx/JmxCollectorTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/ExcludeObjectNamesTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/IncludeAndExcludeObjectNamesTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/IncludeObjectNamesTest.java, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/ExcludeObjectNamesTest/JavaAgent/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/ExcludeObjectNamesTest/JavaAgent/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/ExcludeObjectNamesTest/Standalone/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/ExcludeObjectNamesTest/Standalone/exporter.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/ExcludeObjectNamesTest/Standalone/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeAndExcludeObjectNamesTest/JavaAgent/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeAndExcludeObjectNamesTest/JavaAgent/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeAndExcludeObjectNamesTest/Standalone/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeAndExcludeObjectNamesTest/Standalone/exporter.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeAndExcludeObjectNamesTest/Standalone/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeObjectNamesTest/JavaAgent/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeObjectNamesTest/JavaAgent/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeObjectNamesTest/Standalone/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeObjectNamesTest/Standalone/exporter.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/IncludeObjectNamesTest/Standalone/exporter.yaml
Changed code and documentation to use `allowlistObjectNames` and `denylistObjectNames` in lieu of `whitelistObjectNames` and `blacklistObjectNames`
=> Refactored outdated terms

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
Added code to skip RuntimeMXBean attributes `SystemProperties`, `ClassPath`, `BootClassPath`, and `LibraryPath` since the calls to get the attribute values are very expensive the values are ultimately ignored.
=> Added code to skip RuntimeMXBean attributes

jmx_prometheus_javaagent/src/main/java/io/prometheus/jmx/JavaAgent.java
Prev code would cause jvm to crash as Exception uncatched in javaagent premain. 
So this commit make the BindException checked and output definite error and then exit expectedly.
=> Fix Exceptions are not handled on premain

example_configs/kafka-kraft-3_0_0.yml
@dhoard 
After looking issue #881 and pr #793, i created this pr.
The kraft-related metrics are `raft-metrics`, `raft-channel-metrics`, and `broker-metadata-metrics`, and the reason why these metrics could not be collected with the kafka-2_0_0.yml rules is that the name was set to attrName.
I added the following rules based on kafka-2_0_0.yml file for these metrics.
```yaml
- pattern: "kafka.server<type=raft-metrics><>current-state: ([a-z]+)"
name: kafka_server_raft_metrics_current_state_info
type: GAUGE
value: 1
labels:
"state": "$1"
- pattern: kafka.server<type=(.+)><>([a-z-]+)-total
name: kafka_server_$1_$2_total
type: COUNTER
- pattern: kafka.server<type=(.+)><>([a-z-]+)
name: kafka_server_$1_$2
type: GAUGE
```
And we also get these:
``` …
```
=> Add example config file for kafka kraft mode metrics

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
`JmxScraper#scrapeBean()` uses `ObjectName#toString()` twice per-MBean
_attribute_ to check the MBean name against several special-cases.
`ObjectName#toString()` is quite expensive, because it allocates a new
`char[]` and copies the name data into it, on each call.
Consequently, when there are a large number of number of MBean attributes,
these calls compound and can create performance problems.
Caching the result of `ObjectName#toString()` outside this loop ensures
we only call it once per-MBean.
=> Improve performance of JmxScraper

collector/src/main/java/io/prometheus/jmx/JmxScraper.java
As with #917, we also call `ObjectName#getDomain()` once
per-_attribute_, which is unnecessary and can be expensive when MBeans
contain a large number of attributes.
This is because `ObjectName#getDomain()` allocates a new String, copying
the domain into it.
Signed-off-by: Nick Telford <nick.telford@gmail.com>
=> Cache MBean Domain for performance

README.md
The links and references to jmx exporter were not updated between 0.19 and 0.20; this patch fixes the documentation.
=> Fix documentation links from 0.19 to 0.20

example_configs/hazelcast.yml
Added example config to fetch custom hazelcast metrics from jmx means.
The metrics will be like as following
hazelcast_total_max_get_latency{instance="hz-instance",prefix="map",tag0="\"name=request-trace-cache\"",} 1.0
hazelcast_priority_queue_size{instance="hz-auth-instance",prefix="operation",} 0.0
It can also handle metrics with multiple tags.
hazelcast_connection_type{instance="hazelcastCacheInstance",prefix="tcp.connection, tag0=\"endpoint=[localhost]:5703\"",tag1="\"bindAddress=[testserver]:5703\"",} 1.0
=> Added hazelcast example config

example_configs/weblogic.yml
Added example config to fetch domain names dynamically in metrics from JMX mbean. 
The example metric will be like as below:
weblogic_id{domain="testdomain",} 0.0
The mbean used to fetch it, is the following one:
com.bea:Name=domainName, Type=Domain
=> Updated weblogic jmx config to fetch domain names as a metric

integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/ExcludeObjectNameAttributesTest.java, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/ExcludeObjectNameAttributesTest/JavaAgent/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/ExcludeObjectNameAttributesTest/Standalone/exporter.yaml
Enhanced ExcludeObjectNameAttributesTest to include an example of excluding `java_lang_Memory` attributes `NonHeapMemoryUsage`, `Verbose`, and `ObjectPendingFinalizationCount`.
=> Enhanced ExcludeObjectNameAttributesTest

README.md
Explicitly mention some of the metrics that won't be available if using the JMX exporter as 
standalone http server. 
This will allow to quickly find in the documentation by searching for `jvm_`
Closes #964
=> Mention the metrics not available in http service

integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/MinimalTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/OptionalValueMBeanTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/CompleteHttpServerConfigurationTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPBKDF2WithHmacSHA1Test.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPBKDF2WithHmacSHA256Test.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPBKDF2WithHmacSHA512Test.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationPlaintextTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationSHA1Test.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationSHA256Test.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/BasicAuthenticationSHA512Test.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLAndBasicAuthenticationPBKDF2WithHmacSHA512Test.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithJKSKeyStoreMultipleCertificatesTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithJKSKeyStoreTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithJKSKeyStoreTest2.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithPKCS12KeyStoreMultipleCertificatesTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithPKCS12KeyStoreTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/ssl/SSLWithPKCS12KeyStoreTest2.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/threads/ThreadsConfigurationTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/rmi/ssl/MinimalRMISSLTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/rmi/ssl/RMIRegistrySSLDisabledTest.java
Fixed integration tests.
Specifically, changed this code to match the current standalone build info name.
```java
String buildInfoName =
isJmxExporterModeJavaAgent
? "jmx_prometheus_javaagent"
: "jmx_prometheus_httpserver";
```
=> Fixed integration tests

.circleci/config.yml
Updated CircleCI image. The previous image has been deprecated.
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
=> Updated CircleCI image

example_configs/cassandra.yml
Disabling these two metrics speeds up the scrape time dramatically on our Cassandra cluster - from around 20 seconds to 2-3 seconds.
I think it's worth disabling these by default because it makes the JMX exporter much more usable with Cassandra and this trick isn't particularly obvious.
=> Cassandra: disable two particularly slow metrics

collector/pom.xml, integration_test_suite/jmx_example_application/pom.xml, pom.xml
This is mainly to fix a performance regression that got introduced in JMX Exporter 1.0.0 with the switch to the new Prometheus Java Client.
We traced it down to a problem that others have found (and fixed) before us:
- https://github.com/prometheus/client_java/pull/963
- https://github.com/prometheus/client_java/pull/985
Both of these are fixed in java_client 1.3.2 and performance is back to normal.
For comparison. Assembling metrics took less than 500ms on 0.20 but took over a minute on 1.0.1
btw. the CONTRIBUTING file says to open PRs against `development` but no such branch exists and the `next-release` branch hasn't been updated in three years so I guess `main` is correct and `CONTRIBUTING.md` is wrong? If so, I'm happy to update it.
It also says to address the maintainers using …
=> Updates prometheus java_client to 1.3.2

integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/http/authentication/AuthenticatorClassTest.java, integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/CustomAuthenticator.java
Implemented `UserPrincipal`. `ibmjava:8` doesn't provide `com.sun.security.auth.UserPrincipal`
=> Fixed custom authenticator test for ibmjava:8

integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/opentelemetry/OpenTelemetryEnvironmentVariableTest.java, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/opentelemetry/OpenTelemetryEnvironmentVariableTest/JavaAgent/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/opentelemetry/OpenTelemetryEnvironmentVariableTest/JavaAgent/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/opentelemetry/OpenTelemetryEnvironmentVariableTest/JavaAgent/prometheus.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/opentelemetry/OpenTelemetryEnvironmentVariableTest/Standalone/application.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/opentelemetry/OpenTelemetryEnvironmentVariableTest/Standalone/exporter.sh, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/opentelemetry/OpenTelemetryEnvironmentVariableTest/Standalone/exporter.yaml, integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/opentelemetry/OpenTelemetryEnvironmentVariableTest/Standalone/prometheus.yaml, jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/opentelemetry/OpenTelemetryExporterFactory.java
Fixed code to correctly reference OpenTelemetry environment variables if properties are not defined in the exporter YAML file.
=> Fixed code to correctly reference OpenTelemetry environment variables

examples/cassandra.yml
Cassandra has added a lot more metrics recently. The existing example config results in a scrape time of 15-30 seconds and more than doubles Cassandra's CPU usage in our setup.
This changes the example config to use a whitelist approach with a sample whitelist which takes a much more reasonable 200 ms to scrape.
=> Update Cassandra example config

collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/main/java/io/prometheus/jmx/MatchedRule.java, collector/src/main/java/io/prometheus/jmx/MatchedRuleToMetricSnapshotsConverter.java
Currently the rule matches cache stores unsanitized metric name and labels. That means that sanitization has to be done on each scrape. In my tests that sanitization is responsible for 11% of CPU time (+GC) and 39% of allocations. This cost can be easily avoided by performing the sanitization before caching.
CPU profile (with the relevant parts marked in purple):
Allocation profile (with the relevant parts marked in purple):
=> Cache sanitized name and labels

jmx_prometheus_common/src/main/java/io/prometheus/jmx/common/tools/CustomServiceTransformer.java, jmx_prometheus_isolator_javaagent/pom.xml, jmx_prometheus_isolator_javaagent/src/main/java/io/prometheus/jmx/JarClassLoader.java, jmx_prometheus_javaagent/pom.xml, jmx_prometheus_standalone/pom.xml
Fixed shading. Changed shading prefix to be `e1723a08afd7bca35570fd31a7656f59` md5(Prometheus) due to some shading differences between the Java agent and the Standalone exporter.
=> Fixed shading

integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/JavaDockerImages.java, integration_test_suite/integration_tests/src/main/java/io/prometheus/jmx/test/support/PrometheusDockerImages.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/LocalTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/support/ExporterTestEnvironment.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/support/OpenTelemetryTestEnvironment.java, integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/ExistDb.java, integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/ExistDbMXBean.java, integration_test_suite/jmx_example_application/src/main/java/io/prometheus/jmx/JmxExampleApplication.java
Fixed integration test startup timing issue where integration tests would begin before the test JmxApplication is completely running, resulting is integration test failures.
=> Fixed integration test startup timing issue

collector/pom.xml, collector/src/main/java/io/prometheus/jmx/JmxCollector.java, collector/src/test/java/io/prometheus/jmx/ToSafeNameTest.java, collector/src/test/java/io/prometheus/jmx/ToSnakeAndLowerCaseTest.java, integration_test_suite/integration_tests/src/test/java/io/prometheus/jmx/test/LocalTest.java
Refactored `JmxCollector` methods `toSnakeAndLowerCase` and `toSafeName` to use `charAt` based on profiling and ErrorProne recommendation.
reference: https://errorprone.info/bugpattern/LoopOverCharArray
=> Collector performance tweaks

docs/content/1.1.0/standalone/_index.md, docs/content/1.2.0/standalone/_index.md, docs/content/1.3.0/standalone/_index.md, docs/content/1.4.0/standalone/_index.md
Simple fix for the online documentation, fixing 404's when you try to go to any of the given pages on the standalone documentation.
@fstab
=> Fix standalone agent documentation URLs
